pipeline {
  agent any
  stages {
    stage('Clone Repo') {
      steps {
        git 'https://github.com/Uliwazeer/ci-cd-k8s-app.git'
      }
    }
    stage('Install Dependencies') {
      steps {
        dir('app') {
          sh 'npm install'
        }
      }
    }
    stage('Run Tests') {
      steps {
        dir('app') {
          sh 'npm test'
        }
      }
    }
    stage('Build Docker Image') {
      steps {
        script {
          docker.build('ci-cd-app')
        }
      }
    }
    stage('Push to DockerHub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
          script {
            docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
              docker.image('ci-cd-app').push('latest')
            }
          }
        }
      }
    }
    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl apply -f k8s/deployment.yaml'
        sh 'kubectl apply -f k8s/service.yaml'
        sh 'kubectl apply -f k8s/prometheus.yaml'
      }
    }
  }
}
